export const STATUS_LABELS = {
  approved: '승인 완료',
  accepted: 'Accepted',
  allowed: 'Allowed',
  success: 'Success',
  passed: 'Passed',
  pass: 'Pass',
  merged: 'Merged',
  finished: 'Finished',
  failed: 'Failed',
  danger: 'Danger',
  critical: 'Critical',
  blocked: 'Blocked',
  rejected: '승인 반려',
  'need-check': '확인 필요',
  'need-review': '리뷰 필요',
  reviewing: '검토 중',
  review: 'Review',
  pending: 'Pending',
  running: 'Running',
  warning: 'Warning',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
  open: 'Open',
  manual: 'Manual',
  scheduled: 'Scheduled',
  deployed: 'Deployed',
  requested: 'Requested',
  conditional: 'Conditional',
  'ready-to-merge': 'Ready to Merge',
  created: 'Created',
  skipped: 'Skipped',
  closed: 'Closed',
  draft: 'Draft',
  canceled: 'Canceled',
  none: '-',
}

export const STATUS_TONES = {
  approved: 'success',
  accepted: 'success',
  allowed: 'success',
  success: 'success',
  passed: 'success',
  pass: 'success',
  merged: 'success',
  finished: 'success',
  failed: 'danger',
  danger: 'danger',
  critical: 'danger',
  blocked: 'danger',
  rejected: 'danger',
  'need-check': 'danger',
  'need-review': 'warning',
  reviewing: 'info',
  review: 'info',
  pending: 'neutral',
  running: 'info',
  warning: 'warning',
  high: 'warning',
  medium: 'warning',
  low: 'info',
  open: 'info',
  manual: 'purple',
  scheduled: 'info',
  deployed: 'success',
  requested: 'neutral',
  conditional: 'warning',
  'ready-to-merge': 'success',
  created: 'neutral',
  skipped: 'neutral',
  closed: 'neutral',
  draft: 'purple',
  canceled: 'neutral',
  none: 'neutral',
}
