export const UI_TEXT = {
  navigation: {
    dashboard: 'Dashboard',
    repositories: 'Repositories',
    mergeRequests: 'Merge Requests',
    pipelines: 'Pipelines',
    security: 'Security Validation',
    deploymentTransfer: 'Deployment Transfer',
    audit: 'Audit Log',
    admin: 'Admin Console',
  },
  repositoryNavigation: {
    overview: 'Overview',
    files: 'Files',
    mergeRequests: 'Merge Requests',
    pipelines: 'Pipelines',
    commits: 'Commits',
    branches: 'Branches',
    tags: 'Tags',
    security: 'Security',
    deploymentTransfer: 'Deployment Transfer',
    activity: 'Activity',
    settings: 'Settings',
  },
  status: {
    labels: {
      approved: '승인 완료',
      accepted: 'Accepted',
      allowed: 'Allowed',
      success: 'Success',
      passed: 'Passed',
      pass: 'Pass',
      merged: 'Merged',
      finished: 'Finished',
      failed: 'Failed',
      danger: 'Danger',
      critical: 'Critical',
      blocked: 'Blocked',
      rejected: '승인 반려',
      'need-check': '확인 필요',
      'need-review': '리뷰 필요',
      reviewing: '검토 중',
      review: 'Review',
      pending: 'Pending',
      info: 'Info',
      running: 'Running',
      warning: 'Warning',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      open: 'Open',
      manual: 'Manual',
      scheduled: 'Scheduled',
      deployed: 'Deployed',
      requested: 'Requested',
      conditional: 'Conditional',
      'ready-to-merge': 'Ready to Merge',
      created: 'Created',
      skipped: 'Skipped',
      closed: 'Closed',
      draft: 'Draft',
      canceled: 'Canceled',
      none: '-',
    },
    tones: {
      approved: 'success',
      accepted: 'success',
      allowed: 'success',
      success: 'success',
      passed: 'success',
      pass: 'success',
      merged: 'success',
      finished: 'success',
      failed: 'danger',
      danger: 'danger',
      critical: 'danger',
      blocked: 'danger',
      rejected: 'danger',
      'need-check': 'danger',
      'need-review': 'warning',
      reviewing: 'info',
      review: 'info',
      pending: 'neutral',
      info: 'info',
      running: 'info',
      warning: 'warning',
      high: 'warning',
      medium: 'warning',
      low: 'info',
      open: 'info',
      manual: 'purple',
      scheduled: 'info',
      deployed: 'success',
      requested: 'neutral',
      conditional: 'warning',
      'ready-to-merge': 'success',
      created: 'neutral',
      skipped: 'neutral',
      closed: 'neutral',
      draft: 'purple',
      canceled: 'neutral',
      none: 'neutral',
    },
  },
  actions: {
    refresh: 'Refresh',
    export: 'Export',
    exportCsv: 'Export CSV',
    createRepository: 'Create Repository',
    newMergeRequest: 'New Merge Request',
    newTransferRequest: 'New Transfer Request',
    runPipeline: 'Run Pipeline',
    runValidation: 'Run Validation',
    viewDetail: 'View Detail',
    view: 'View',
    submitRequest: 'Submit Request',
    cancel: 'Cancel',
  },
  messages: {
    empty: {
      table: '표시할 데이터가 없습니다.',
      noSearchResults: '검색 결과가 없습니다.',
      noSearchResultsDescription: '검색어나 필터 조건을 변경해 보세요.',
    },
    notFound: {
      repository: 'Repository not found',
      deploymentTransfer: 'Deployment transfer not found',
    },
    demo: {
      readOnlySettings: 'Demo read-only 화면입니다. 실제 저장 기능은 연결되어 있지 않습니다.',
      filePreviewPlaceholder: '상세 파일 뷰어는 데모 범위 밖이라 미리보기 placeholder로 표시합니다.',
    },
  },
  pages: {
    dashboard: {
      title: 'Dashboard',
      description: '개발 업무, 승인, 검증, 보안 이슈를 한 화면에서 확인하는 업무 대시보드',
    },
    repositories: {
      title: 'Repository',
      description: '프로젝트 Repository를 관리하고 Pipeline과 보안 상태를 한눈에 확인하세요.',
    },
    mergeRequests: {
      title: 'Merge Requests',
      description: '전체 Repository의 MR 승인, 검증, 병합 상태를 확인하는 화면',
    },
    pipelines: {
      title: 'Pipelines',
      description: '전체 Repository의 Pipeline 실행 상태와 실패 이력을 확인하는 화면',
    },
    security: {
      title: 'Security Validation',
      description: 'Repository와 Merge Request 단위의 보안 검증 상태와 차단 항목을 확인하는 화면',
    },
    deploymentTransfer: {
      title: 'Deployment Transfer',
      description: '운영 반영 요청, 승인 상태, 배포 전 검증 조건을 확인하는 화면',
    },
    audit: {
      title: 'Audit Log',
      description: '개발 활동, 승인, 보안 검증, 정책 변경 이력을 추적하는 감사 로그 화면',
    },
    repositoryFiles: {
      title: 'Files',
      description: '현재 Repository의 파일 구조와 주요 소스 파일을 확인하는 화면',
    },
    repositoryCommits: {
      title: 'Commits',
      description: '현재 Repository의 커밋 이력과 변경 내역을 확인하는 화면',
    },
    repositoryBranches: {
      title: 'Branches',
      description: '브랜치 상태, 보호 정책, 최신 커밋을 확인하는 화면',
    },
    repositoryTags: {
      title: 'Tags',
      description: '배포 기준 태그와 릴리즈 이력을 확인하는 화면',
    },
    repositoryActivity: {
      title: 'Activity',
      description: '현재 Repository의 주요 개발 활동과 시스템 이벤트를 확인하는 화면',
    },
    repositorySettings: {
      title: 'Settings',
      description: 'Repository 정책과 기본 설정을 확인하는 화면',
    },
    repositoryMergeRequests: {
      title: 'Merge Requests',
      description: '현재 Repository에 연결된 Merge Request의 승인, Pipeline, 보안 상태를 확인합니다.',
    },
    repositoryPipelines: {
      title: 'Pipelines',
      description: '현재 Repository의 Pipeline 실행 상태, 실패 Job, 실행 이력을 확인하는 화면',
    },
    repositoryDeploymentTransfer: {
      title: 'Deployment Transfer',
      description: '특정 Repository의 운영이관 요청 목록입니다.',
    },
  },
  adminPages: {
    admin: {
      title: 'Admin Console',
      description: '조직, 권한, 정책, 연동, 테마 설정을 관리하는 관리자 콘솔',
    },
  },
  deploymentTransfer: {
    title: 'Deployment Transfer',
    description: '운영 반영 요청, 승인 상태, 배포 전 검증 조건을 확인하는 화면',
  },
  dashboardAi: {
    title: 'gitddn AI Assistant',
    description: '승인, 파이프라인 실패, 보안 차단, 운영이관 준비 상태를 빠르게 확인하세요.',
    inputPlaceholder: 'Ask gitddn AI about MR, pipeline, security, deployment...',
  },
  topHeader: {
    adminConsole: 'Admin Console',
    backToUserPlatform: 'Back to User Platform',
    organizationSwitched: 'Organization switched to',
  },
  globalSearch: {
    placeholder: 'Search repositories, MRs, pipelines, security...',
    empty: '검색 결과가 없습니다.',
    hint: 'Repository, MR, Pipeline, Security, Deployment, Audit, Policy를 검색하세요.',
  },
  quickCreate: {
    label: 'Create',
    repository: 'Repository',
    mergeRequest: 'Merge Request',
    deploymentTransfer: 'Deployment Transfer',
    securityValidation: 'Security Validation',
    policy: 'Policy',
    unavailable: 'Demo 화면에서는 목록 화면으로 이동합니다.',
  },
  notifications: {
    title: 'Notifications',
    markAllRead: 'Mark all as read',
    allRead: 'All notifications marked as read',
    empty: '새 알림이 없습니다.',
  },
  help: {
    title: 'Help',
    demoGuide: 'Demo Guide',
    keyboardShortcuts: 'Keyboard Shortcuts',
    contactAdmin: 'Contact Admin',
    about: 'About gitddn',
    demoGuideTitle: 'gitddn Demo Guide',
    demoGuideBody: 'Repository, MR, Pipeline, Security, Deployment Transfer, Audit, Admin Console 흐름을 mock 데이터로 체험할 수 있습니다.',
  },
  userMenu: {
    myProfile: 'My Profile',
    myActivity: 'My Activity',
    preferences: 'Preferences',
    signOut: 'Sign out',
    demoOnly: 'Demo action only',
  },
  organizations: {
    storageKey: 'gitddn.organization',
  },
  deploymentTransferCreate: {
    title: 'New Deployment Transfer',
    description: '운영 반영 요청 정보를 입력하고 배포 전 검증 조건을 확인하는 화면',
    submit: 'Submit Transfer Request',
    draft: 'Save as Draft',
    cancel: 'Cancel',
    submitted: 'Deployment transfer request submitted',
    draftSaved: 'Deployment transfer draft saved',
    formTitle: 'Transfer Request',
    gatePreview: 'Validation / Gate Preview',
    summaryPreview: 'Summary Preview',
    recommendedActions: 'Recommended Actions',
    expectedApprovalPolicy: 'Release Manager approval required',
  },
  auth: {
    signIn: 'Sign in',
    signOut: 'Sign out',
    email: 'Email',
    password: 'Password',
    invalidCredentials: 'Invalid email or password',
    signedOut: 'Signed out successfully',
  },
  login: {
    productName: 'gitddn',
    description: '금융권 DevSecOps Governance Platform',
    formDescription: '사내 인증, SSO, LDAP 확장을 고려한 데모 로그인입니다.',
    demoAccounts: 'Demo accounts',
  },
  roles: {
    admin: 'Admin',
    internal: 'Internal User',
    external: 'External Developer',
  },
  accessDenied: {
    title: 'Access Denied',
    description: 'You do not have permission to access this page.',
    backToDashboard: 'Back to Dashboard',
    signInAnother: 'Sign in with another account',
  },
}
