const NAVIGATION_LABELS = {
  dashboard: '홈',
  repositories: '저장소',
  mergeRequests: 'MR 대시보드',
  pipelines: 'Pipelines',
  security: '보안',
  deploymentTransfer: '운영 대시보드',
  audit: '감사',
  admin: '관리자 콘솔',
}

const REPOSITORY_NAVIGATION_LABELS = {
  overview: '개요',
  files: '파일',
  mergeRequests: 'Merge Requests',
  pipelines: NAVIGATION_LABELS.pipelines,
  commits: 'Commits',
  branches: 'Branches',
  gitGraph: 'Git Graph',
  tags: 'Tags',
  security: NAVIGATION_LABELS.security,
  deploymentTransfer: '운영이관',
  activity: 'Activity',
  settings: '설정',
}

export const UI_TEXT = {
  navigation: NAVIGATION_LABELS,
  repositoryNavigation: REPOSITORY_NAVIGATION_LABELS,
  status: {
    labels: {
      approved: '승인 완료',
      accepted: 'Accepted',
      allowed: 'Allowed',
      success: 'Success',
      passed: 'Passed',
      pass: 'Pass',
      merged: 'Merged',
      finished: 'Finished',
      failed: 'Failed',
      danger: 'Danger',
      critical: 'Critical',
      blocked: 'Blocked',
      rejected: '승인 반려',
      'need-check': '확인 필요',
      'need-review': '리뷰 필요',
      reviewing: '검토 중',
      review: 'Review',
      pending: 'Pending',
      info: 'Info',
      running: 'Running',
      warning: 'Warning',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      open: 'Open',
      manual: 'Manual',
      scheduled: 'Scheduled',
      deployed: 'Deployed',
      requested: 'Requested',
      conditional: 'Conditional',
      'ready-to-merge': 'Ready to Merge',
      created: 'Created',
      skipped: 'Skipped',
      closed: 'Closed',
      draft: 'Draft',
      canceled: 'Canceled',
      none: '-',
    },
    tones: {
      approved: 'success',
      accepted: 'success',
      allowed: 'success',
      success: 'success',
      passed: 'success',
      pass: 'success',
      merged: 'success',
      finished: 'success',
      failed: 'danger',
      danger: 'danger',
      critical: 'danger',
      blocked: 'danger',
      rejected: 'danger',
      'need-check': 'danger',
      'need-review': 'warning',
      reviewing: 'info',
      review: 'info',
      pending: 'neutral',
      info: 'info',
      running: 'info',
      warning: 'warning',
      high: 'warning',
      medium: 'warning',
      low: 'info',
      open: 'info',
      manual: 'purple',
      scheduled: 'info',
      deployed: 'success',
      requested: 'neutral',
      conditional: 'warning',
      'ready-to-merge': 'success',
      created: 'neutral',
      skipped: 'neutral',
      closed: 'neutral',
      draft: 'purple',
      canceled: 'neutral',
      none: 'neutral',
    },
  },
  actions: {
    refresh: '새로고침',
    export: '내보내기',
    exportCsv: 'CSV 내보내기',
    createRepository: 'Repository 생성',
    newMergeRequest: '새 Merge Request',
    newTransferRequest: '새 운영이관 요청',
    runPipeline: 'Pipeline 실행',
    runValidation: '검증 실행',
    viewDetail: '상세 보기',
    view: '보기',
    submitRequest: '요청 제출',
    cancel: '취소',
    close: '닫기',
    search: '검색',
    create: '생성',
  },
  messages: {
    empty: {
      table: '표시할 데이터가 없습니다.',
      noSearchResults: '검색 결과가 없습니다.',
      noSearchResultsDescription: '검색어나 필터 조건을 변경해 보세요.',
    },
    notFound: {
      repository: 'Repository를 찾을 수 없습니다.',
      deploymentTransfer: '운영이관 요청을 찾을 수 없습니다.',
    },
    demo: {
      readOnlySettings: 'Demo read-only 화면입니다. 실제 저장 기능은 연결되어 있지 않습니다.',
      filePreviewPlaceholder: '상세 파일 뷰어는 데모 범위 밖이라 미리보기 placeholder로 표시합니다.',
    },
  },
  pages: {
    dashboard: {
      title: NAVIGATION_LABELS.dashboard,
      description: '개발 업무, 승인, 검증, 보안 이슈를 한 화면에서 확인하는 업무 대시보드',
    },
    repositories: {
      title: NAVIGATION_LABELS.repositories,
      description: '프로젝트 Repository를 관리하고 Pipeline과 보안 상태를 한눈에 확인하세요.',
    },
    mergeRequests: {
      title: NAVIGATION_LABELS.mergeRequests,
      description: '전체 Repository의 MR 승인, 검증, 병합 상태를 확인하는 화면',
    },
    pipelines: {
      title: NAVIGATION_LABELS.pipelines,
      description: '전체 Repository의 Pipeline 실행 상태와 실패 이력을 확인하는 화면',
    },
    security: {
      title: NAVIGATION_LABELS.security,
      description: 'Repository와 Merge Request 단위의 보안 검증 상태와 차단 항목을 확인하는 화면',
    },
    deploymentTransfer: {
      title: NAVIGATION_LABELS.deploymentTransfer,
      description: '운영 반영 요청, 승인 상태, 배포 전 검증 조건을 확인하는 화면',
    },
    audit: {
      title: NAVIGATION_LABELS.audit,
      description: '개발 활동, 승인, 보안 검증, 정책 변경 이력을 추적하는 감사 로그 화면',
    },
    repositoryFiles: {
      title: REPOSITORY_NAVIGATION_LABELS.files,
      description: '현재 Repository의 파일 구조와 주요 소스 파일을 확인하는 화면',
    },
    repositoryCommits: {
      title: REPOSITORY_NAVIGATION_LABELS.commits,
      description: '현재 Repository의 커밋 이력과 변경 내역을 확인하는 화면',
    },
    repositoryBranches: {
      title: REPOSITORY_NAVIGATION_LABELS.branches,
      description: 'Branch 상태, 보호 정책, 최신 Commit을 확인합니다.',
    },
    repositoryGitGraph: {
      title: REPOSITORY_NAVIGATION_LABELS.gitGraph,
      description: '현재 Repository의 브랜치 흐름과 커밋 그래프를 확인하는 화면',
    },
    repositoryTags: {
      title: REPOSITORY_NAVIGATION_LABELS.tags,
      description: '배포 기준 태그와 릴리즈 이력을 확인합니다.',
    },
    repositorySecurity: {
      title: REPOSITORY_NAVIGATION_LABELS.security,
      description: '현재 Repository의 보안 검증 상태와 정책 판단 결과를 확인하는 화면',
    },
    repositoryActivity: {
      title: REPOSITORY_NAVIGATION_LABELS.activity,
      description: '현재 Repository의 주요 개발 활동과 시스템 이벤트를 확인하는 화면',
    },
    repositorySettings: {
      title: REPOSITORY_NAVIGATION_LABELS.settings,
      description: 'Repository 정책과 기본 설정을 확인하는 화면',
    },
    repositoryMergeRequests: {
      title: REPOSITORY_NAVIGATION_LABELS.mergeRequests,
      description: '현재 Repository에 연결된 Merge Request의 승인, Pipeline, 보안 상태를 확인합니다.',
    },
    repositoryPipelines: {
      title: REPOSITORY_NAVIGATION_LABELS.pipelines,
      description: '현재 Repository의 Pipeline 실행 상태, 실패 Job, 실행 이력을 확인하는 화면',
    },
    repositoryDeploymentTransfer: {
      title: REPOSITORY_NAVIGATION_LABELS.deploymentTransfer,
      description: '특정 Repository의 운영이관 요청 목록입니다.',
    },
  },
  adminPages: {
    admin: {
      title: NAVIGATION_LABELS.admin,
      description: '조직, 권한, 정책, 연동, 테마 설정을 관리하는 관리자 콘솔',
    },
  },
  deploymentTransfer: {
    title: '운영이관',
    description: '운영 반영 요청, 승인 상태, 배포 전 검증 조건을 확인하는 화면',
  },
  dashboardAi: {
    title: 'gitddn AI Assistant',
    description: '승인, 파이프라인 실패, 보안 차단, 운영이관 준비 상태를 빠르게 확인하세요.',
    inputPlaceholder: 'Ask gitddn AI about MR, pipeline, security, deployment...',
  },
  topHeader: {
    adminConsole: '관리자 메뉴',
    backToUserPlatform: '사용자 플랫폼으로 돌아가기',
    organizationSwitched: '조직이 전환되었습니다:',
    helpMockNotice: 'Quick Create, Global Search, 알림 Drawer는 mock 데이터 기반으로 동작합니다.',
  },
  globalSearch: {
    placeholder: 'Repositories, MR, Pipeline, 보안 항목 검색...',
    empty: '검색 결과가 없습니다.',
    hint: 'Repository, MR, Pipeline, Security, Deployment, Audit, Policy를 검색하세요.',
  },
  quickCreate: {
    label: '생성',
    repository: 'Repository',
    mergeRequest: 'Merge Request',
    deploymentTransfer: 'Deployment Transfer',
    securityValidation: 'Security Validation',
    policy: 'Policy',
    unavailable: 'Demo 화면에서는 목록 화면으로 이동합니다.',
  },
  notifications: {
    title: '알림',
    markAllRead: '모두 읽음 처리',
    allRead: '모든 알림을 읽음 처리했습니다.',
    empty: '새 알림이 없습니다.',
  },
  help: {
    title: '도움말',
    demoGuide: 'Demo Guide',
    keyboardShortcuts: 'Keyboard Shortcuts',
    contactAdmin: 'Contact Admin',
    about: 'About gitddn',
    demoGuideTitle: 'gitddn Demo Guide',
    demoGuideBody: 'Repository, MR, Pipeline, Security, Deployment Transfer, Audit, Admin Console 흐름을 mock 데이터로 체험할 수 있습니다.',
  },
  userMenu: {
    myProfile: '내 프로필',
    myActivity: '내 활동',
    preferences: '환경설정',
    signOut: '로그아웃',
    demoOnly: '데모 전용 동작입니다',
  },
  common: {
    workspace: 'Workspace',
    governanceAdmin: 'Governance Admin',
    currentRepository: '현재 Repository',
    repository: 'Repository',
    repositoryName: 'Repository 이름',
    group: '그룹',
    groupPath: '그룹 경로',
    language: '언어',
    status: '상태',
    role: '역할',
    permission: '권한',
    pipeline: 'Pipeline',
    security: '보안',
    updated: '업데이트',
    updatedAt: '업데이트 시각',
    defaultBranch: '기본 Branch',
    visibility: '공개 범위',
    favorite: '즐겨찾기',
    favorites: '즐겨찾기',
    nonFavorites: '즐겨찾기 아님',
    openMr: '열린 MR',
    owner: '담당자',
    author: '작성자',
    trigger: 'Trigger',
    commit: 'Commit',
    jobs: 'Jobs',
    lastSync: '마지막 동기화',
    preview: '미리보기',
    path: '경로',
    description: '설명',
  },
  summary: {
    totalMrs: '전체 MR',
    readyToMerge: 'Merge 가능',
    totalRepositories: '전체 Repositories',
    active: '활성',
    reviewRequired: '리뷰 필요',
    securityBlocked: '보안 차단',
    reviewRequiredMrs: '리뷰 필요 MR',
    myOpenMrs: '내 열린 MR',
    failedPipelines: '실패한 Pipelines',
    pendingActions: '대기 중 작업',
    todayAuditEvents: '오늘 감사 이벤트',
    totalRequests: '전체 요청',
    pendingApproval: '승인 대기',
    readyToDeploy: '배포 가능',
    blocked: '차단',
    approved: '승인 완료',
    scheduled: '예약됨',
    totalPipelines: '전체 Pipelines',
    passed: '통과',
    failed: '실패',
    running: '실행 중',
    manualRequired: '수동 처리 필요',
    totalValidations: '전체 검증',
    blockedMrs: '차단된 MR',
    criticalIssues: 'Critical 이슈',
    warning: '경고',
  },
  sections: {
    nextUp: '다음 작업 / 조치 필요',
    myRepositories: '내 Repositories',
    mergeRequestsOverview: 'Merge Requests 현황',
    pipelineHealth: 'Pipeline 상태',
    securityAttention: '보안 확인 필요',
    recentAuditEvents: '최근 감사 이벤트',
    recentActivity: '최근 Activity',
    governanceOverview: 'Governance 현황',
    recentAdminAudit: '최근 관리자 감사',
    policyHealth: '정책 상태',
  },
  tables: {
    mrId: 'MR ID',
    title: '제목',
    review: '리뷰',
    approval: '승인',
    branch: 'Branch',
    failedJobs: '실패 Job',
    duration: '소요 시간',
    securityId: '보안 ID',
    policy: '정책',
    criticalHigh: 'Critical / High',
    lastChecked: '마지막 확인',
  },
  filters: {
    status: '상태',
    language: '언어',
    visibility: '공개 범위',
    favorite: '즐겨찾기',
    protected: '보호 여부',
    severity: '심각도',
    relatedMr: '연결된 MR',
    repositorySearch: 'Repository 이름, 그룹, 설명 검색',
    pipelineSearch: 'Pipeline ID, repository, branch, commit, author, MR 검색',
    mergeRequestSearch: 'MR title, repository, branch, author 검색',
    deploymentTransferSearch: 'Transfer, repository, MR, requester, environment 검색',
    repositoryDeploymentTransferSearch: 'Transfer, MR, requester 검색',
    securitySearch: 'Security ID, Repository, MR, Author, Vulnerability 검색',
    auditSearch: 'Audit ID, Event, Actor, Target, Message, IP 검색',
    targetEnvironment: '대상 환경',
    requestedBy: '요청자',
    approvalStatus: '승인 상태',
    securityStatus: '보안 상태',
    pipelineStatus: 'Pipeline 상태',
  },
  adminNavigation: {
    organizationRoles: '조직 / 권한',
    repositoryPolicy: 'Repository 정책',
    projectTemplates: '프로젝트 템플릿 관리',
    mrApprovalPolicy: 'MR 정책',
    securityPolicy: 'Pipeline / 보안 정책',
    deploymentPolicy: '운영이관 정책',
    auditPolicy: '감사 정책',
    notificationPolicy: '알림 / 연동',
    integration: '연동',
    themeBranding: '테마 / 브랜딩',
  },
  organizations: {
    storageKey: 'gitddn.organization',
  },
  designToken: {
    button: 'Design Token',
    title: 'Design Token',
    description: 'Light.json 또는 dark.json 형식의 Ant Design theme token을 붙여넣거나 업로드해 즉시 적용합니다.',
    mode: '테마 모드',
    light: 'Light',
    dark: 'Dark',
    lightJson: 'Light.json',
    darkJson: 'dark.json',
    preview: '테마 미리보기',
    applyLight: 'Light 적용',
    applyDark: 'Dark 적용',
    applyCurrent: '현재 모드 적용',
    reset: '기본값으로 초기화',
    close: '닫기',
    appliedLight: 'Light 테마 토큰을 적용했습니다.',
    appliedDark: 'Dark 테마 토큰을 적용했습니다.',
    appliedCurrent: '현재 테마 토큰을 적용했습니다.',
    resetDone: '기본 테마 토큰으로 복구했습니다.',
  },
  deploymentTransferCreate: {
    title: 'New Deployment Transfer',
    description: '운영 반영 요청 정보를 입력하고 배포 전 검증 조건을 확인하는 화면',
    submit: 'Submit Transfer Request',
    draft: 'Save as Draft',
    cancel: 'Cancel',
    submitted: 'Deployment transfer request submitted',
    draftSaved: 'Deployment transfer draft saved',
    formTitle: 'Transfer Request',
    gatePreview: 'Validation / Gate Preview',
    summaryPreview: 'Summary Preview',
    recommendedActions: 'Recommended Actions',
    expectedApprovalPolicy: 'Release Manager approval required',
  },
  auth: {
    signIn: 'Sign in',
    signOut: 'Sign out',
    email: 'Email',
    password: 'Password',
    invalidCredentials: 'Invalid email or password',
    signedOut: 'Signed out successfully',
  },
  login: {
    productName: 'gitddn',
    description: '금융권 DevSecOps Governance Platform',
    formDescription: '사내 인증, SSO, LDAP 확장을 고려한 데모 로그인입니다.',
    demoAccounts: '데모 계정',
    ssoReady: 'SSO ready',
    ldapReady: 'LDAP ready',
    roleBasedGovernance: 'Role-based governance',
  },
  roles: {
    admin: 'Admin',
    internal: 'Internal User',
    external: 'External Developer',
  },
  accessDenied: {
    title: 'Access Denied',
    description: 'You do not have permission to access this page.',
    backToDashboard: 'Back to Dashboard',
    signInAnother: 'Sign in with another account',
  },
  adminSummary: {
    organizations: '조직',
    users: '사용자',
    activePolicies: '활성 정책',
    policyViolations: '정책 위반',
    pendingRequests: '대기 중 요청',
    integrationStatus: '연동 상태',
    activeRules: '개 활성 규칙',
    healthy: '정상',
  },
}
