export const UI_TEXT = {
  navigation: {
    dashboard: '대시보드',
    repositories: 'Repositories',
    mergeRequests: 'Merge Requests',
    pipelines: 'Pipelines',
    security: '보안',
    deploymentTransfer: '운영이관',
    audit: '감사',
    admin: '관리자',
  },
  repositoryNavigation: {
    overview: '개요',
    files: '파일',
    mergeRequests: 'Merge Requests',
    pipelines: 'Pipelines',
    commits: 'Commits',
    branches: 'Branches',
    tags: 'Tags',
    security: '보안',
    deploymentTransfer: '운영이관',
    activity: '활동',
    settings: '설정',
  },
  status: {
    labels: {
      approved: '승인 완료',
      accepted: '승인',
      allowed: '허용',
      success: '성공',
      passed: '통과',
      pass: '통과',
      merged: 'Merged',
      finished: '완료',
      failed: '실패',
      danger: '위험',
      critical: '긴급',
      blocked: '차단',
      rejected: '승인 반려',
      'need-check': '확인 필요',
      'need-review': '리뷰 필요',
      reviewing: '검토 중',
      review: '리뷰',
      pending: '대기 중',
      info: '정보',
      running: '실행 중',
      warning: '경고',
      high: '높음',
      medium: '중간',
      low: '낮음',
      open: 'Open',
      manual: '수동',
      scheduled: '예약됨',
      deployed: '배포 완료',
      requested: '요청됨',
      conditional: '조건부',
      'ready-to-merge': 'Merge 가능',
      created: '생성됨',
      skipped: '건너뜀',
      closed: 'Closed',
      draft: 'Draft',
      canceled: '취소됨',
      none: '-',
    },
    tones: {
      approved: 'success',
      accepted: 'success',
      allowed: 'success',
      success: 'success',
      passed: 'success',
      pass: 'success',
      merged: 'success',
      finished: 'success',
      failed: 'danger',
      danger: 'danger',
      critical: 'danger',
      blocked: 'danger',
      rejected: 'danger',
      'need-check': 'danger',
      'need-review': 'warning',
      reviewing: 'info',
      review: 'info',
      pending: 'neutral',
      info: 'info',
      running: 'info',
      warning: 'warning',
      high: 'warning',
      medium: 'warning',
      low: 'info',
      open: 'info',
      manual: 'purple',
      scheduled: 'info',
      deployed: 'success',
      requested: 'neutral',
      conditional: 'warning',
      'ready-to-merge': 'success',
      created: 'neutral',
      skipped: 'neutral',
      closed: 'neutral',
      draft: 'purple',
      canceled: 'neutral',
      none: 'neutral',
    },
  },
  actions: {
    refresh: '새로고침',
    export: '내보내기',
    exportCsv: 'CSV 내보내기',
    createRepository: 'Repository 생성',
    newMergeRequest: '새 Merge Request',
    newTransferRequest: '새 운영이관 요청',
    runPipeline: 'Pipeline 실행',
    runValidation: '검증 실행',
    viewDetail: '상세 보기',
    view: '보기',
    submitRequest: '요청 제출',
    cancel: '취소',
  },
  messages: {
    empty: {
      table: '표시할 데이터가 없습니다.',
      noSearchResults: '검색 결과가 없습니다.',
      noSearchResultsDescription: '검색어나 필터 조건을 변경해 보세요.',
    },
    notFound: {
      repository: 'Repository를 찾을 수 없습니다.',
      deploymentTransfer: '운영이관 요청을 찾을 수 없습니다.',
    },
    demo: {
      readOnlySettings: 'Demo read-only 화면입니다. 실제 저장 기능은 연결되어 있지 않습니다.',
      filePreviewPlaceholder: '상세 파일 뷰어는 데모 범위 밖이라 미리보기 placeholder로 표시합니다.',
    },
  },
  pages: {
    dashboard: {
      title: '대시보드',
      description: '개발 업무, 승인, 검증, 보안 이슈를 한 화면에서 확인하는 업무 대시보드',
    },
    repositories: {
      title: 'Repository',
      description: '프로젝트 Repository를 관리하고 Pipeline과 보안 상태를 한눈에 확인하세요.',
    },
    mergeRequests: {
      title: 'Merge Requests',
      description: '전체 Repository의 MR 승인, 검증, 병합 상태를 확인하는 화면',
    },
    pipelines: {
      title: 'Pipelines',
      description: '전체 Repository의 Pipeline 실행 상태와 실패 이력을 확인하는 화면',
    },
    security: {
      title: '보안 검증',
      description: 'Repository와 Merge Request 단위의 보안 검증 상태와 차단 항목을 확인하는 화면',
    },
    deploymentTransfer: {
      title: '운영이관',
      description: '운영 반영 요청, 승인 상태, 배포 전 검증 조건을 확인하는 화면',
    },
    audit: {
      title: '감사 로그',
      description: '개발 활동, 승인, 보안 검증, 정책 변경 이력을 추적하는 감사 로그 화면',
    },
    repositoryFiles: {
      title: '파일',
      description: '현재 Repository의 파일 구조와 주요 소스 파일을 확인하는 화면',
    },
    repositoryCommits: {
      title: 'Commits',
      description: '현재 Repository의 커밋 이력과 변경 내역을 확인하는 화면',
    },
    repositoryBranches: {
      title: 'Branches',
      description: '브랜치 상태, 보호 정책, 최신 커밋을 확인하는 화면',
    },
    repositoryTags: {
      title: 'Tags',
      description: '배포 기준 태그와 릴리즈 이력을 확인하는 화면',
    },
    repositoryActivity: {
      title: '활동',
      description: '현재 Repository의 주요 개발 활동과 시스템 이벤트를 확인하는 화면',
    },
    repositorySettings: {
      title: '설정',
      description: 'Repository 정책과 기본 설정을 확인하는 화면',
    },
    repositoryMergeRequests: {
      title: 'Merge Requests',
      description: '현재 Repository에 연결된 Merge Request의 승인, Pipeline, 보안 상태를 확인합니다.',
    },
    repositoryPipelines: {
      title: 'Pipelines',
      description: '현재 Repository의 Pipeline 실행 상태, 실패 Job, 실행 이력을 확인하는 화면',
    },
    repositoryDeploymentTransfer: {
      title: '운영이관',
      description: '특정 Repository의 운영이관 요청 목록입니다.',
    },
  },
  adminPages: {
    admin: {
      title: '관리자 콘솔',
      description: '조직, 권한, 정책, 연동, 테마 설정을 관리하는 관리자 콘솔',
    },
  },
  deploymentTransfer: {
    title: '운영이관',
    description: '운영 반영 요청, 승인 상태, 배포 전 검증 조건을 확인하는 화면',
  },
  dashboardAi: {
    title: 'gitddn AI Assistant',
    description: '승인, 파이프라인 실패, 보안 차단, 운영이관 준비 상태를 빠르게 확인하세요.',
    inputPlaceholder: 'MR, Pipeline, 보안, 운영이관에 대해 gitddn AI에게 질문하세요.',
  },
  topHeader: {
    adminConsole: '관리자 콘솔',
    backToUserPlatform: '사용자 화면으로 돌아가기',
    organizationSwitched: '조직이 변경되었습니다:',
  },
  globalSearch: {
    placeholder: 'Repository, MR, Pipeline, 보안 항목을 검색하세요.',
    empty: '검색 결과가 없습니다.',
    hint: 'Repository, MR, Pipeline, 보안, 운영이관, 감사 로그, 정책을 검색하세요.',
  },
  quickCreate: {
    label: '생성',
    repository: 'Repository',
    mergeRequest: 'Merge Request',
    deploymentTransfer: '운영이관',
    securityValidation: '보안 검증',
    policy: '정책',
    unavailable: 'Demo 화면에서는 목록 화면으로 이동합니다.',
  },
  notifications: {
    title: '알림',
    markAllRead: '모두 읽음 처리',
    allRead: '모든 알림을 읽음 처리했습니다.',
    empty: '새 알림이 없습니다.',
  },
  help: {
    title: '도움말',
    demoGuide: 'Demo 가이드',
    keyboardShortcuts: '단축키',
    contactAdmin: '관리자 문의',
    about: 'gitddn 정보',
    demoGuideTitle: 'gitddn Demo 가이드',
    demoGuideBody: 'Repository, MR, Pipeline, 보안, 운영이관, 감사 로그, 관리자 콘솔 흐름을 mock 데이터로 체험할 수 있습니다.',
  },
  userMenu: {
    myProfile: '내 프로필',
    myActivity: '내 활동',
    preferences: '환경설정',
    signOut: '로그아웃',
    demoOnly: 'Demo 전용 동작입니다.',
  },
  organizations: {
    storageKey: 'gitddn.organization',
  },
  designToken: {
    button: 'Design Token',
    title: 'Design Token',
    description: 'Light.json 또는 dark.json 형식의 Ant Design theme token을 붙여넣거나 업로드해 즉시 적용합니다.',
    mode: '테마 모드',
    light: 'Light',
    dark: 'Dark',
    lightJson: 'Light.json',
    darkJson: 'dark.json',
    preview: '테마 미리보기',
    applyLight: 'Light 적용',
    applyDark: 'Dark 적용',
    applyCurrent: '현재 모드 적용',
    reset: '기본값으로 초기화',
    close: '닫기',
    appliedLight: 'Light theme token이 적용되었습니다.',
    appliedDark: 'Dark theme token이 적용되었습니다.',
    appliedCurrent: '현재 theme token이 적용되었습니다.',
    resetDone: '기본 theme token으로 복원되었습니다.',
  },
  deploymentTransferCreate: {
    title: '새 운영이관 요청',
    description: '운영 반영 요청 정보를 입력하고 배포 전 검증 조건을 확인하는 화면',
    submit: '운영이관 요청 제출',
    draft: '임시저장',
    cancel: '취소',
    submitted: '운영이관 요청이 제출되었습니다.',
    draftSaved: '운영이관 요청이 임시저장되었습니다.',
    formTitle: '운영이관 요청 정보',
    gatePreview: '검증 / Gate 미리보기',
    summaryPreview: '요약 미리보기',
    recommendedActions: '권장 조치',
    expectedApprovalPolicy: 'Release Manager 승인이 필요합니다.',
  },
  auth: {
    signIn: '로그인',
    signOut: '로그아웃',
    email: '이메일',
    password: '비밀번호',
    invalidCredentials: '이메일 또는 비밀번호가 올바르지 않습니다.',
    signedOut: '로그아웃되었습니다.',
  },
  login: {
    productName: 'gitddn',
    description: '금융권 DevSecOps Governance Platform',
    formDescription: '사내 인증, SSO, LDAP 확장을 고려한 데모 로그인입니다.',
    demoAccounts: 'Demo 계정',
  },
  roles: {
    admin: '관리자',
    internal: '내부 사용자',
    external: '외부 개발자',
  },
  accessDenied: {
    title: '접근 권한 없음',
    description: '이 페이지에 접근할 권한이 없습니다.',
    backToDashboard: '대시보드로 돌아가기',
    signInAnother: '다른 계정으로 로그인',
  },
}
